meta_product_name: "My League"
meta_title: "My League - The best app to track your sports performances with friends :)"
meta_description: "With My League you will track all your sports performances with friends so easily"
meta_image: "iphone.png"
twitter_account: "@my_league_pro"